### ISSUE TITLE
Heart rate data

### ISSUE THREAD

**Issue by salwator** [salwator/uRunScope#4]
Introduce heart rate data to Training model:

### TODO:
- [x] HRM gpx data retrieve
- [x] missing data handling
- [x] min/max/avg calculation
