### ISSUE TITLE
Add basic training views

### ISSUE THREAD

**Issue by salwator** [salwator/uRunScope#5]
### TODO:
- [ ] training view with file upload
- [ ] training details view
- [ ] training list view
